/**
 * Nepal Electoral Geography & Party Data
 *
 * Complete reference data for Nepal's federal election structure:
 * - 7 Provinces
 * - 77 Districts
 * - 165 House of Representatives (HoR) constituencies
 * - Major political parties
 */

const PARTIES = {
  NC: {
    id: "NC",
    name: "Nepali Congress",
    shortName: "NC",
    color: "#1565c0",
    symbol: "tree",
  },
  UML: {
    id: "UML",
    name: "CPN (UML)",
    shortName: "UML",
    color: "#c62828",
    symbol: "sun",
  },
  NCP: {
    id: "NCP",
    name: "Nepali Communist Party",
    shortName: "NCP",
    color: "#8b0000",
    symbol: "hammer",
  },
  RSP: {
    id: "RSP",
    name: "Rastriya Swatantra Party",
    shortName: "RSP",
    color: "#e65100",
    symbol: "key",
  },
  RPP: {
    id: "RPP",
    name: "Rastriya Prajatantra Party",
    shortName: "RPP",
    color: "#6a1b9a",
    symbol: "crown",
  },
  JSP: {
    id: "JSP",
    name: "Janata Samajbadi Party, Nepal",
    shortName: "JSP",
    color: "#2e7d32",
    symbol: "cycle",
  },
  LOSP: {
    id: "LOSP",
    name: "Loktantrik Samajwadi Party",
    shortName: "LoPa",
    color: "#00838f",
    symbol: "pen",
  },
  JMMP: {
    id: "JMMP",
    name: "Janamat Party",
    shortName: "JaMaPa",
    color: "#4e342e",
    symbol: "bell",
  },
  NUP: {
    id: "NUP",
    name: "Nagarik Unmukti Party",
    shortName: "NUP",
    color: "#00695c",
    symbol: "fist",
  },
  UNP: {
    id: "UNP",
    name: "Ujaylo Nepal Party",
    shortName: "UNP",
    color: "#ff8f00",
    symbol: "bulb",
  },
  MAOIST: {
    id: "MAOIST",
    name: "Nepal Communist Party (Maoist)",
    shortName: "Maoist",
    color: "#b71c1c",
    symbol: "sickle",
  },
  SSP: {
    id: "SSP",
    name: "Shram Sanskriti Party",
    shortName: "SSP",
    color: "#33691e",
    symbol: "wheat",
  },
  RMP: {
    id: "RMP",
    name: "Rastriya Mukti Party Nepal",
    shortName: "RMP",
    color: "#004d40",
    symbol: "chain",
  },
  NWPP: {
    id: "NWPP",
    name: "Nepal Workers Peasants Party",
    shortName: "NWPP",
    color: "#d50000",
    symbol: "axe",
  },
  IND: {
    id: "IND",
    name: "Independent",
    shortName: "Ind",
    color: "#757575",
    symbol: "none",
  },
};

const PROVINCES = [
  {
    id: 1,
    name: "Koshi Pradesh",
    nameNp: "कोशी प्रदेश",
    capital: "Biratnagar",
    totalConstituencies: 28,
    districts: [
      { id: "taplejung", name: "Taplejung", constituencies: 1 },
      { id: "panchthar", name: "Panchthar", constituencies: 1 },
      { id: "ilam", name: "Ilam", constituencies: 2 },
      { id: "jhapa", name: "Jhapa", constituencies: 5 },
      { id: "morang", name: "Morang", constituencies: 6 },
      { id: "sunsari", name: "Sunsari", constituencies: 4 },
      { id: "dhankuta", name: "Dhankuta", constituencies: 1 },
      { id: "terhathum", name: "Terhathum", constituencies: 1 },
      { id: "sankhuwasabha", name: "Sankhuwasabha", constituencies: 1 },
      { id: "bhojpur", name: "Bhojpur", constituencies: 1 },
      { id: "solukhumbu", name: "Solukhumbu", constituencies: 1 },
      { id: "okhaldhunga", name: "Okhaldhunga", constituencies: 1 },
      { id: "khotang", name: "Khotang", constituencies: 1 },
      { id: "udayapur", name: "Udayapur", constituencies: 2 },
    ],
  },
  {
    id: 2,
    name: "Madhesh Pradesh",
    nameNp: "मधेश प्रदेश",
    capital: "Janakpur",
    totalConstituencies: 32,
    districts: [
      { id: "saptari", name: "Saptari", constituencies: 3 },
      { id: "siraha", name: "Siraha", constituencies: 4 },
      { id: "dhanusha", name: "Dhanusha", constituencies: 5 },
      { id: "mahottari", name: "Mahottari", constituencies: 4 },
      { id: "sarlahi", name: "Sarlahi", constituencies: 4 },
      { id: "rautahat", name: "Rautahat", constituencies: 4 },
      { id: "bara", name: "Bara", constituencies: 4 },
      { id: "parsa", name: "Parsa", constituencies: 4 },
    ],
  },
  {
    id: 3,
    name: "Bagmati Pradesh",
    nameNp: "बागमती प्रदेश",
    capital: "Hetauda",
    totalConstituencies: 33,
    districts: [
      { id: "dolakha", name: "Dolakha", constituencies: 1 },
      { id: "sindhupalchok", name: "Sindhupalchok", constituencies: 2 },
      { id: "rasuwa", name: "Rasuwa", constituencies: 1 },
      { id: "nuwakot", name: "Nuwakot", constituencies: 2 },
      { id: "dhading", name: "Dhading", constituencies: 2 },
      { id: "kathmandu", name: "Kathmandu", constituencies: 10 },
      { id: "bhaktapur", name: "Bhaktapur", constituencies: 2 },
      { id: "lalitpur", name: "Lalitpur", constituencies: 3 },
      { id: "kavrepalanchok", name: "Kavrepalanchok", constituencies: 2 },
      { id: "ramechhap", name: "Ramechhap", constituencies: 1 },
      { id: "sindhuli", name: "Sindhuli", constituencies: 2 },
      { id: "makwanpur", name: "Makwanpur", constituencies: 2 },
      { id: "chitwan", name: "Chitwan", constituencies: 3 },
    ],
  },
  {
    id: 4,
    name: "Gandaki Pradesh",
    nameNp: "गण्डकी प्रदेश",
    capital: "Pokhara",
    totalConstituencies: 18,
    districts: [
      { id: "gorkha", name: "Gorkha", constituencies: 2 },
      { id: "lamjung", name: "Lamjung", constituencies: 1 },
      { id: "tanahu", name: "Tanahu", constituencies: 2 },
      { id: "kaski", name: "Kaski", constituencies: 3 },
      { id: "syangja", name: "Syangja", constituencies: 2 },
      { id: "parbat", name: "Parbat", constituencies: 1 },
      { id: "myagdi", name: "Myagdi", constituencies: 1 },
      { id: "baglung", name: "Baglung", constituencies: 2 },
      { id: "nawalparasi_east", name: "Nawalparasi (East)", constituencies: 2 },
      { id: "manang", name: "Manang", constituencies: 1 },
      { id: "mustang", name: "Mustang", constituencies: 1 },
    ],
  },
  {
    id: 5,
    name: "Lumbini Pradesh",
    nameNp: "लुम्बिनी प्रदेश",
    capital: "Deukhuri",
    totalConstituencies: 26,
    districts: [
      { id: "nawalparasi_west", name: "Nawalparasi (West)", constituencies: 2 },
      { id: "rupandehi", name: "Rupandehi", constituencies: 5 },
      { id: "kapilvastu", name: "Kapilvastu", constituencies: 3 },
      { id: "palpa", name: "Palpa", constituencies: 2 },
      { id: "arghakhanchi", name: "Arghakhanchi", constituencies: 1 },
      { id: "gulmi", name: "Gulmi", constituencies: 2 },
      { id: "dang", name: "Dang", constituencies: 3 },
      { id: "banke", name: "Banke", constituencies: 3 },
      { id: "bardiya", name: "Bardiya", constituencies: 2 },
      { id: "pyuthan", name: "Pyuthan", constituencies: 1 },
      { id: "rolpa", name: "Rolpa", constituencies: 1 },
      { id: "rukum_east", name: "Rukum (East)", constituencies: 1 },
    ],
  },
  {
    id: 6,
    name: "Karnali Pradesh",
    nameNp: "कर्णाली प्रदेश",
    capital: "Birendranagar",
    totalConstituencies: 12,
    districts: [
      { id: "rukum_west", name: "Rukum (West)", constituencies: 1 },
      { id: "salyan", name: "Salyan", constituencies: 1 },
      { id: "surkhet", name: "Surkhet", constituencies: 2 },
      { id: "dailekh", name: "Dailekh", constituencies: 2 },
      { id: "jajarkot", name: "Jajarkot", constituencies: 1 },
      { id: "dolpa", name: "Dolpa", constituencies: 1 },
      { id: "jumla", name: "Jumla", constituencies: 1 },
      { id: "kalikot", name: "Kalikot", constituencies: 1 },
      { id: "mugu", name: "Mugu", constituencies: 1 },
      { id: "humla", name: "Humla", constituencies: 1 },
    ],
  },
  {
    id: 7,
    name: "Sudurpashchim Pradesh",
    nameNp: "सुदूरपश्चिम प्रदेश",
    capital: "Godawari",
    totalConstituencies: 16,
    districts: [
      { id: "bajura", name: "Bajura", constituencies: 1 },
      { id: "bajhang", name: "Bajhang", constituencies: 1 },
      { id: "darchula", name: "Darchula", constituencies: 1 },
      { id: "baitadi", name: "Baitadi", constituencies: 1 },
      { id: "dadeldhura", name: "Dadeldhura", constituencies: 1 },
      { id: "doti", name: "Doti", constituencies: 1 },
      { id: "achham", name: "Achham", constituencies: 2 },
      { id: "kailali", name: "Kailali", constituencies: 5 },
      { id: "kanchanpur", name: "Kanchanpur", constituencies: 3 },
    ],
  },
];

// Generate the full constituency list from province/district data
function generateConstituencies() {
  const constituencies = [];
  let globalId = 1;

  for (const province of PROVINCES) {
    for (const district of province.districts) {
      for (let num = 1; num <= district.constituencies; num++) {
        constituencies.push({
          id: globalId,
          slug: `${district.id}-${num}`,
          name: `${district.name}-${num}`,
          districtId: district.id,
          districtName: district.name,
          provinceId: province.id,
          provinceName: province.name,
          number: num,
        });
        globalId++;
      }
    }
  }

  return constituencies;
}

// Common Nepali names pool for generating realistic candidate data
const FIRST_NAMES = [
  "Ram",
  "Shyam",
  "Hari",
  "Krishna",
  "Bishnu",
  "Sita",
  "Gita",
  "Laxmi",
  "Prakash",
  "Sushil",
  "Rajendra",
  "Narayan",
  "Ganesh",
  "Manoj",
  "Rajan",
  "Sarita",
  "Kamala",
  "Durga",
  "Parvati",
  "Sunita",
  "Bishwas",
  "Deepak",
  "Suresh",
  "Mahesh",
  "Ramesh",
  "Dinesh",
  "Suman",
  "Binod",
  "Arjun",
  "Bhim",
  "Khadga",
  "Surya",
  "Chandra",
  "Indra",
  "Dev",
  "Tek",
  "Bal",
  "Purna",
  "Dhan",
  "Nanda",
  "Gopal",
  "Mohan",
  "Roshan",
  "Santosh",
  "Kabita",
  "Sabina",
  "Rekha",
  "Anita",
  "Mina",
  "Geeta",
  "Pramila",
  "Bimala",
  "Shanti",
  "Tara",
  "Uma",
  "Radha",
  "Januka",
  "Kopila",
];

const LAST_NAMES = [
  "Sharma",
  "Thapa",
  "Adhikari",
  "Gurung",
  "Tamang",
  "Rai",
  "Limbu",
  "Magar",
  "Shrestha",
  "Maharjan",
  "Joshi",
  "Poudel",
  "Bhattarai",
  "Khatri",
  "Chhetri",
  "Bhandari",
  "Pandey",
  "Dahal",
  "Neupane",
  "Subedi",
  "Acharya",
  "Koirala",
  "Karki",
  "Basnet",
  "Rijal",
  "Ghimire",
  "Sapkota",
  "Lamichhane",
  "Regmi",
  "Devkota",
  "Pokharel",
  "Pant",
  "Oli",
  "Gautam",
  "Tiwari",
  "Yadav",
  "Mandal",
  "Shah",
  "Mishra",
  "Singh",
  "Mehta",
  "Thakur",
  "Chaudhary",
  "Dangol",
];

const CONSTITUENCIES = generateConstituencies();
const PARTY_IDS = Object.keys(PARTIES);
const MAJOR_PARTIES = [
  "NC",
  "UML",
  "NCP",
  "RSP",
  "RPP",
  "JSP",
  "JMMP",
  "NUP",
  "UNP",
];

module.exports = {
  PARTIES,
  PROVINCES,
  CONSTITUENCIES,
  MAJOR_PARTIES,
  PARTY_IDS,
  FIRST_NAMES,
  LAST_NAMES,
};
